---
- name: Manage systemd as service user
  become: true
  become_user: "{{ docmost_service_user }}"
  block:
    - name: Restart docmost
      ansible.builtin.systemd_service:
        name: docmost.service
        state: restarted
