---
- name: Manage systemd as service user
  become: true
  become_user: "{{ docmost_service_user }}"
  block:
    - name: Reload systemd user daemon
      ansible.builtin.systemd:
        scope: user
        daemon_reload: true

    - name: Restart docmost
      become: true
      become_user: "{{ docmost_service_user }}"
      ansible.builtin.systemd:
        name: docmost.service
        state: restarted
