---
- name: Fetch NPM secrets from Vault
  ansible.builtin.import_role:
    name: vault
    tasks_from: fetch_secrets.yml
  vars:
    vault_secret_path: nginx_proxy_manager
    vault_secret_mapping:
      - key: username
        var_name: npm_username
      - key: password
        var_name: npm_password

- name: Authenticate with NPM and get token
  uri:
    url: "{{ npm_api_url }}/tokens"
    method: POST
    validate_certs: no
    status_code: 200
    body_format: json
    body:
      identity: "{{ npm_username }}"
      secret: "{{ npm_password }}"
    headers:
      Content-Type: application/json
  register: npm_auth
  delegate_to: localhost
  no_log: true

- name: Set auth token fact
  ansible.builtin.set_fact:
    npm_token: "{{ npm_auth.json.token }}"
  no_log: true
  delegate_to: localhost
