[podman_hosts]
plane ansible_host=plane.lan
docmost ansible_host=docmost.lan

[podman_hosts:vars]
ansible_user=debian
ansible_ssh_private_key_file=~/projects/homelab/priv.key
ansible_python_interpreter=/usr/bin/python3
