# inventory/hosts.yml
all:
  children:
    hardware:
      hosts:
        fritzbox:
          ansible_host: 192.168.178.1
        pihole:
          ansible_host: 192.168.178.53
        printer:
          ansible_host: 192.168.178.106
        homeserver:
          ansible_host: 192.168.178.10
    virtual_machines:
      vars:
        ansible_user: debian
        ansible_ssh_private_key_file: ~/projects/homelab/priv.key
      hosts:
        database:
          ansible_host: database
        office:
          ansible_host: office
        media:
          ansible_host: media
        utility:
          ansible_host: utility
    postgres_host:
      hosts:
        postgres_server:
          ansible_host: database-pg-prod
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/projects/homelab/tofu/infrastructure/keys/database-pg-prod.key
