# inventory/hosts.yml
all:
  children:
    hardware:
      hosts:
        fritzbox:
          ansible_host: 192.168.178.1
        pihole:
          ansible_host: 192.168.178.53
        printer:
          ansible_host: 192.168.178.106
        homeserver:
          ansible_host: 192.168.178.10
    virtual_machines:
      vars:
        ansible_user: debian
      hosts:
        database:
          ansible_host: database
        backup:
          ansible_host: backup
        office:
          ansible_host: office
        media:
          ansible_host: media
        utility:
          ansible_host: utility
