---
- name: Deploy {{ plane_app_name }} MinIO container Quadlet
  become: true
  become_user: "{{ plane_service_user }}"
  ansible.builtin.template:
    src: plane-minio.container.j2
    dest: "{{ plane_quadlet_dir }}/plane-minio.container"
    owner: "{{ plane_service_user }}"
    group: "{{ plane_service_user }}"
    mode: "0644"
  notify: Restart plane-minio service
