---
- name: Setup disks for docmost
  ansible.builtin.import_role:
    name: os_debian
    tasks_from: setup_additional_disks.yml
  vars:
    disks:
      - scsi_num: 1
        mount_path: "{{ docmost_data_dir }}"

- name: Generate and store secrets in Vault
  ansible.builtin.import_role:
    name: vault
    tasks_from: store_secrets.yml
  vars:
    vault_secret_path: "{{ docmost_app_name }}"
    vault_force_update: false
    vault_secrets:
      - key: app_secret
        length: 48
      - key: db_password
        length: 32
      - key: db_user
        value: "{{ docmost_db_user }}"

- name: Fetch docmost secrets from Vault
  ansible.builtin.import_role:
    name: vault
    tasks_from: fetch_secrets.yml
  vars:
    vault_secret_path: "{{ docmost_app_name }}"
    vault_secret_mapping:
      - key: app_secret
        var_name: docmost_app_secret
      - key: db_password
        var_name: docmost_db_password
      - key: db_user
        var_name: docmost_db_user

- name: Provision docmost database
  include_role:
    name: postgres
    tasks_from: provision_database.yml
  vars:
    database_name: "{{ docmost_db_name }}"
    database_user: "{{ docmost_db_user }}"
    database_user_password: "{{ docmost_db_password }}"

- name: Setup podman user
  ansible.builtin.import_role:
    name: podman
    tasks_from: init_podman_user
  vars:
    podman_user:
      name: "{{ docmost_service_user }}"

- name: Setup directories
  ansible.builtin.import_tasks: directories.yml

- name: Install Docmost
  ansible.builtin.import_tasks: install.yml

- name: Configure NPM proxy host
  ansible.builtin.import_role:
    name: nginx_proxy_manager
    tasks_from: proxy_hosts.yml
  vars:
    npm_proxy_hosts:
      - domain_names:
          - "{{docmost_app_domain}}"
        forward_host: "{{ ansible_host }}"
        forward_port: "{{ docmost_port }}"
