---
- name: Check if {{ docmost_app_name }} secrets already exist in Vault
  community.hashi_vault.vault_kv2_get:
    engine_mount_point: "{{ vault_mount_path }}"
    path: "{{ docmost_app_name }}"
  register: existing_secrets

  no_log: false
  ignore_errors: true
  delegate_to: localhost

- name: Store {{ docmost_app_name }} secrets in Vault
  community.hashi_vault.vault_kv2_write:
    engine_mount_point: "{{ vault_mount_path }}"
    path: "{{ docmost_app_name }}"
    data:
      app_secret: "{{ lookup('password', '/dev/null length=48 chars=ascii_letters,digits') }}"
      db_password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
      db_user: "{{ docmost_db_user }}"
  no_log: true

  when: existing_secrets.failed or force_regenerate | default(false)
  delegate_to: localhost
