---
- name: Setup Proxy Hosts
  ansible.builtin.import_playbook: proxy

- name: Setup Databases
  ansible.builtin.import_playbook: databases
- name: Setup Apps
  ansible.builtin.import_playbook: apps
