---
lan_domain: "lan.schwarzkopf.center"
pihole_ip: 192.168.178.53

vault_mount_path: kv-apps

postgres_host: "{{ hostvars['postgres_server'].ansible_host }}"
postgres_port: 5432

npm_api_url: "https://npm.{{lan_domain}}/api"
