---
- name: Setup disks for {{ paperless_app_name }}
  ansible.builtin.import_role:
    name: os_debian
    tasks_from: setup_additional_disks.yml
  vars:
    os_disks:
      - scsi_num: 2
        mount_path: "{{ paperless_mount_dir }}"

- name: Generate and store {{ paperless_app_name }} secrets in vault
  ansible.builtin.import_tasks: secrets_generate.yml

- name: fetch and {{ paperless_app_name }} secrets from vault
  ansible.builtin.import_tasks: secrets_fetch.yml

- name: Provision {{ paperless_app_name }} database
  ansible.builtin.import_role:
    name: postgres
    tasks_from: provision_database.yml
  vars:
    database_name: "{{ paperless_db_name }}"
    database_user: "{{ paperless_db_user }}"
    database_user_password: "{{ paperless_db_password }}"

- name: Setup podman user
  ansible.builtin.import_role:
    name: podman
    tasks_from: setup_rootless_users
  vars:
    podman_users:
      - "{{ paperless_service_user }}"

- name: Setup directories
  ansible.builtin.import_tasks: directories.yml

- name: Deploy application
  ansible.builtin.import_tasks: install.yml

- name: Setup SMB
  ansible.builtin.import_tasks: smb.yml
  when: paperless_smb_enabled

- name: Configure NPM proxy host
  ansible.builtin.import_role:
    name: nginx_proxy_manager
    tasks_from: proxy_hosts.yml
  vars:
    npm_proxy_hosts:
      - domain_names:
          - "{{paperless_app_domain}}"
        forward_host: "{{ ansible_host }}"
        forward_port: "{{ paperless_port }}"
