---
- name: Check if {{ paperless_app_name }} secrets already exist in Vault
  community.hashi_vault.vault_kv2_get:
    engine_mount_point: "{{ vault_mount_path }}"
    path: "{{ paperless_app_name }}"
  register: existing_secrets
  no_log: false
  ignore_errors: true
  delegate_to: localhost

- name: Store {{ paperless_app_name }} secrets in Vault
  community.hashi_vault.vault_kv2_write:
    engine_mount_point: "{{ vault_mount_path }}"
    path: "{{ paperless_app_name }}"
    data:
      db_user: "{{ paperless_db_user }}"
      db_password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
      secret_key: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"
      smb_password: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters,digits') }}"
  no_log: true

  when: existing_secrets.failed or force_regenerate | default(false)
  delegate_to: localhost
