---
- name: Fetch "{{ paperless_app_name }}" secrets from Vault
  community.hashi_vault.vault_kv2_get:
    engine_mount_point: "{{ vault_mount_path }}"
    path: "{{ paperless_app_name }}"
  register: paperless_vault_secrets
  no_log: true
  delegate_to: localhost

- name: Set "{{ paperless_app_name }}" secrets as facts
  ansible.builtin.set_fact:
    paperless_db_password: "{{ paperless_vault_secrets.secret.db_password }}"
    paperless_secret_key: "{{ paperless_vault_secrets.secret.secret_key }}"
    paperless_smb_password: "{{ paperless_vault_secrets.secret.smb_password }}"
  no_log: true
  delegate_to: localhost
