---
- name: Generate and store secrets in Vault
  ansible.builtin.import_role:
    name: vault
    tasks_from: store_secrets.yml
  vars:
    vault_secret_path: "{{ immich_app_name }}"
    vault_force_update: false
    vault_secrets:
      - key: db_user
        value: "{{ immich_db_user }}"
      - key: db_password
        length: 32

- name: Fetch docmost secrets from Vault
  ansible.builtin.import_role:
    name: vault
    tasks_from: fetch_secrets.yml
  vars:
    vault_secret_path: "{{ immich_app_name }}"
    vault_secret_mapping:
      - key: db_user
        var_name: immich_db_user
      - key: db_password
        var_name: immich_db_password

- name: Provision {{ immich_app_name }} database
  ansible.builtin.import_role:
    name: postgres
    tasks_from: provision_database.yml
  vars:
    postgres_port: "{{ postgres_vectorchord_port }}"
    postgres_instance_name: "postgres-vectorchord"
    database_name: "{{ immich_db_name }}"
    database_user: "{{ immich_db_user }}"
    database_user_password: "{{ immich_db_password }}"

- name: Setup disks for {{ immich_app_name }}
  ansible.builtin.import_role:
    name: os_debian
    tasks_from: setup_additional_disks.yml
  vars:
    disks:
      - scsi_num: 2
        mount_path: "{{ immich_mount_dir }}"

- name: Setup podman user
  ansible.builtin.import_role:
    name: podman
    tasks_from: init_podman_user
  vars:
    podman_user:
      name: "{{ immich_service_user }}"

- name: Setup directories
  ansible.builtin.import_tasks: directories.yml

- name: Deploy containers
  ansible.builtin.import_tasks: containers.yml

- name: Configure NPM proxy host
  ansible.builtin.import_role:
    name: nginx_proxy_manager
    tasks_from: proxy_hosts.yml
  vars:
    npm_proxy_hosts:
      - domain_names:
          - "{{ immich_app_domain }}"
        forward_host: "{{ ansible_host }}"
        forward_port: "{{ immich_port }}"
        allow_websocket_upgrade: true
