#cloud-config

hostname: ${HOSTNAME}
fqdn: ${HOSTNAME}.lan
prefer_fqdn_over_hostname: true

package_update: true
package_upgrade: true

ssh_authorized_keys:
  - ${public_key_openssh}

device_aliases:
  data_disk: /dev/sdb

disk_setup:
  data_disk:
    table_type: gpt
    layout: true
    overwrite: false

fs_setup:
  - label: data
    filesystem: ext4
    device: data_disk
    partition: auto
    overwrite: false

mounts:
  - [data_disk.1, ${MOUNT_PATH}, auto, "defaults,nofail", "0", "2"]

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - software-properties-common

runcmd:
  # install docker
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt update
  - apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
  - usermod -aG docker "$(id -nu 1000)"

  # Create and secure the data directory
  - chown 1000:1000 -R ${MOUNT_PATH}
  - chown 5050:5050 -R ${PGADMIN_DATA_PATH}
  - su - ubuntu -c "cd /home/ubuntu && docker compose up -d"

# Create docker-compose.yml for PostgreSQL
write_files:
  - path: /home/ubuntu/docker-compose.yml
    owner: ubuntu:ubuntu
    permissions: "0644"
    encoding: b64
    content: ${DOCKER_COMPOSE_ENCODED}
