---
- name: Delete secrets in Vault
  community.hashi_vault.vault_kv2_delete:
    engine_mount_point: "{{ vault_mount_path }}"
    path: "{{ vault_secret_path }}"
  no_log: true
  delegate_to: localhost
