# vars example:
# vault_secret_path: "path/to/secret"
# vault_secret_mapping:
#   - key: app_secret
#     var_name: docmost_app_secret
#   - key: db_password
#     var_name: docmost_db_password

---
- name: Fetch secrets from Vault
  community.hashi_vault.vault_kv2_get:
    engine_mount_point: "{{ vault_mount_path }}"
    path: "{{ vault_secret_path }}"
  register: vault_fetched_secrets
  no_log: true
  become: false
  delegate_to: localhost

- name: Set secrets as facts
  ansible.builtin.set_fact:
    "{{ item.var_name }}": "{{ vault_fetched_secrets.secret[item.key] }}"
  loop: "{{ vault_secret_mapping }}"
  no_log: true
  become: false
  delegate_to: localhost
