---
- name: Installing podman-compose via apt
  ansible.builtin.apt:
    name: podman-compose
    state: present
  register: apt_compose
  failed_when: false
  when: ansible_facts['os_family'] == "Debian"

- name: Verify podman-compose installation
  ansible.builtin.command: podman-compose --version
  register: podman_compose_version_output
  changed_when: false

- name: Print podman-compose version
  ansible.builtin.debug:
    msg: "podman-compose installed: {{ podman_compose_version_output.stdout }}"
