---
leafwiki_quadlet_dir: /etc/containers/systemd

leafwiki_app_name: "leafwiki"
leafwiki_data_dir: "/mnt/leafwiki_data"
leafwiki_service_user: "{{ leafwiki_app_name }}"

leafwiki_version: "v0.9.2"

leafwiki_image_registry: ghcr.io
leafwiki_image: "{{leafwiki_image_registry}}/perber/leafwiki:{{leafwiki_version}}"

leafwiki_port: 8081
leafwiki_app_domain: "wiki.{{ lan_domain }}"
leafwiki_app_url: "https://{{ leafwiki_app_domain }}"

leafwiki_enable_revision: true
leafwiki_jwt_secret: "{{ lookup('ansible.builtin.password', '/dev/null', length=15) }}"
leafwiki_public_access: true
