---
- name: Set ownership of mount point for pod user
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ docmost_data_dir }}"
    owner: "{{ docmost_service_user }}"
    group: "{{ docmost_service_user }}"
    mode: "0750"
    recurse: true
