---
- name: Fetch "{{ docmost_app_name }}" secrets from Vault
  community.hashi_vault.vault_kv2_get:
    engine_mount_point: "{{ vault_mount_path }}"
    path: "{{ docmost_app_name }}"
  register: docmost_vault_secrets
  no_log: true
  become: false
  delegate_to: localhost

- name: Set "{{ docmost_app_name }}" secrets as facts
  ansible.builtin.set_fact:
    docmost_app_secret: "{{ docmost_vault_secrets.secret.app_secret }}"
    docmost_db_password: "{{ docmost_vault_secrets.secret.db_password }}"
  no_log: true
  become: false
  delegate_to: localhost
